#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon_barra_32x32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAIGNIUk0AAHolAACAgwAA+f8A"
    "AIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAGYktHRAD/AP8A/6C9p5MAAAAJcEhZcwAACxMA"
    "AAsTAQCanBgAAAQaSURBVFjDxZdbbBRlFMd/3zczu53tZdleaDFWY73QEIOCiIgJRgyRF01Q"
    "I8YgGBN9gGohEQ0qgg00BEQSi6IhVUR9kIAXEojGBDE+KCQqMSFoRAhYoFDa7m53d9rZme/4"
    "sPUewLa74czLPHzn/H/fOXMm5ygRES6j2QDHkqfpzvVhK01JaERQRkApAPIY6txx3FDdiG3E"
    "cPDMEbqzJQIQQRyLMOqgwmGITBZXRWmKN2ALoJXC0XbxAYbFnXSWm57vpOJEN0daHuC3WZOx"
    "UoP4YQ4NIICU4MEY/FiUpm17uHbvZ9Qe/omb29/BSWUwtgakAFAqE2PQlkVV3hAQY7Cskkg6"
    "i+0NIlqDlBDAhCGRmIufGuDVQ9/jA+5gmq7Z0/Hqq9F+gChV6IJSiJeVu3hZj/UPPU3iiga+"
    "3rkeqy9F77RmdD4ofIyK4gOEQYhbGSPdm2TN/FaabpzIkk0r6SMk1BDxfFRoEKVAKG4JwiCg"
    "Il7J+a6zrJj7OJNmTKH1jTY8L4fOekQyHogAhf9BUTMQBgEV4+J0/XKctQ8vZdaDc1mwsoV0"
    "fxIUKKvQ4upffkXJQBgExGurOfrDYVbPW8ycRfNYuLqVTH+qIK7UBX3HDBAGAVU1CQ7tP8C6"
    "R5/hviULmL/8CVI9vSilLioOMrYShEHAuPE1HNi7n82L21i0ppU5C+fR330ey7Yu4KX+9maN"
    "HqAgXstXO/bQuWIjizte5PZ7Z9Pf3YNlXzysICgsHBUbHUAYhFQ31PH5tl1sX9XBsq1rmHr3"
    "TJJne7GckYUc2WkRjBES9TXs3PQ2n3S8x3Pvb2DSjCkke0YuPiIAEQER4rUJPmjfwhfvfszK"
    "Ha/RNLmZdG//JdM+JgARQQGVtQk6V7zCN7v3sWrXZq68/hoG+pKjFv9fAGIMytK45TE6Wl7m"
    "54M/0vbpFuoaJ5BJpsckfkkAExpsxyZa7rLpyRc4ffQkbbvforyqgmwqc5FWGzWAQokBIxhj"
    "iJS7iBHaH1lGbiDL6o9eJxpz8bK5ooj/F0AMYcTBd6O4WuOd7mHdY88Sdct4aUcHSsFQzsOy"
    "iiP+DwBlhDAWJXbyHBO//I5TV41n+fo3ubqxgaVb1xLmA/JDeXQRxf8CEMHYmmg6x8yWjdT/"
    "epQmhPunT+LWznZk0CcIArRV/AFKAygRwkiEqhOniB/vIhmvJ06EJXfeQRixCYd8tC7N9FaI"
    "qhRWEJAbX8dQooqK1DkMebrqE6h8ACW4+R9mA4hSaD9PbkI13254iqYP93F+WjNn7rkNJzM8"
    "wZYSQCuFtm3sQZ/emZM5d9ct6NDgZHJFv70CBOvPktoKyAx59A+kcLQN6TQM70dSgtQrpfDz"
    "ecqNg1Jga6WZWnMdx4IojrYLG00JrQDg05howLZs1OVez38Hr/jT8vaEHMcAAAAASUVORK5C"
    "YII=")
geticon_barra_32x32Data = icon_barra_32x32.GetData
geticon_barra_32x32Image = icon_barra_32x32.GetImage
geticon_barra_32x32Bitmap = icon_barra_32x32.GetBitmap

