#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon_cortante = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAIGNIUk0AAHolAACAgwAA+f8A"
    "AIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAJcEhZcwAACxMAAAsTAQCanBgAAAQdSURBVEjH"
    "tZZNTFxVFMf/59773nwyw4d8jIqpCFYbsEZLsIvagLqpRhdtiDYx1qaSGrGbLtGktXFjUqPR"
    "2jbURDeNysIY20SiJHVjFREUUCiWaUMtX4UywzDMzPu4x8VAwY2k8Hpz8xZvcX/3/z/nnnOI"
    "mXEnlwIQT4xPLt5UJLxCEcjWTmmg8MHiSqVZd08MTaa9B4RgVkVjigFBwiCpQCyEVwAAwgEz"
    "FABm7RpShwIqmQYAoo0zGEuxFaTZDfrv+mVk8wfn7GhImwa52iOrAECAWRsyODlbdfbC44c+"
    "9d9IWkVhcjQ8CogAwIJkyhpufe76C/X1b7THOvtyZREQSHsgReRvSprNRDq+r2nspe3bDp+p"
    "PdrBgpyQnxzXAwUAoLVWUqUWkeNLrz+bjRU+sf9E5NJ4rixKrsYGHuMSgDRDEIQAoNK5/iMv"
    "ZqpKtr/64QNnuuzCECu57sivAFgQAFaCXG3Mp21fYKCtOTw6ua21XWYsqyi0PruWLWIGiFwN"
    "Wv46LgR1nz6og7Jp1zsV3/fnSiNgkKtJ89p7GaBuKbAL/HY0aBcEtKHswpAT9gOkTZXadHey"
    "ujL2Q39xX3zo8PMQghyXpVjRzSBeMiD/hwCdzsBhEBSBARJsFw/GY+d7i/66Gr46FTvXWzA2"
    "IVw79t3vJf2Xkw/de2Xvjq1vn63oGhhs2+0GTHN2gQ3pBkyZzrKS2jTkYpal0H5TprNsqLnq"
    "cg6GwUyu43xx7Sfu6t70TY/jNwhgInI1S0HM0MxS5B+EHQkY89nSn4fMVPpK887AxM3i3vhU"
    "Y51/OhEZvj69Y4uRTJf0xceffrTs4vDIy09O7tnZUtWoWJDMWFMNNbNNj/x/OpKrXZ/hm0lt"
    "ee9rlcmNtO6qOdXZe3xfce9ozanOno8ORIf+qTvyZc/HB7Ye/UrknHzpVABAJLK2kXXWzHaD"
    "WZvqj3f3Vn1+oaHlE6s8TK5W8xmRtX2zKSOxKCzHN5tSqSwHI8S8KosEsRRrbyXJ1eZcenT/"
    "U90nD7owao91uAFTGwoASwIRS5k/EAAIt98AiFgK343kwv1lFz97k1xdf6hdkGMVhUkvW7Cc"
    "VKsU3OZiJdWiJbPW4Ft7BtqaQ3/PVJ/uzJVG8glCmm/1LrU+AID8Hf1TianG2mTtfbXHOu45"
    "/5sbMu2CQP6R5svoRnskK2km0k7I9+uJ16Ya66L918p//NOOBpkI4A0pWGFIQY7rm01dbnlm"
    "pqHm4fe/LRwe62vbnQ+JN11+KfLTyVRNrPtky0z9ZiwXRg8UrLZLLVosRe/xV3gh41/IsvRo"
    "TllhCIJmtZBdKgrslUX/sQuglWMVAEEkhZBeTnZgSJGvRQQs5DJzqaQhFHs0qxCRZdshbRBB"
    "CRKPlVTHHZ/XAKuyqEJJRXd6fP8XARUYFIonv8kAAAAASUVORK5CYII=")
geticon_cortanteData = icon_cortante.GetData
geticon_cortanteImage = icon_cortante.GetImage
geticon_cortanteBitmap = icon_cortante.GetBitmap

