#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon_seta_selecionar_32x32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAIGNIUk0AAHolAACAgwAA+f8A"
    "AIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAJcEhZcwAACxMAAAsTAQCanBgAAAQ2SURBVEjH"
    "tZZ/aFZlFMfPOfe59/1x3/e9++E0q63QaTN1jDFn0abvIokoXRJDG+Fmsx+MEkZlw2hIEJax"
    "smwrmFmYSElI0IigBlGE/UBII4xZo1rN0Wyb3fe9v5/n6Y/Ntvbz3Zz3r8tzn3s/9znnfL/n"
    "oJQSrubFAKBnuK/fGmRIC4VCQF8EeZGslTn5TEjx7YVz/emFB+igLTOWMglAiCqx/wBCCERE"
    "xCsBAAAFICUwAJAAEqQEKQFAynA86jtu4AWk0LwZo18DoHFLQESe63W9/aFrOXpWXHAhxZWG"
    "bQyAAIEfGHk5qYGh1i1NZ7u+iRgxNaSKgC8MAACQ0LXsTY/UoIZHHn3uWFPr3/0DsVwDpBRC"
    "LAQAMfD8WE4i+eBWAjr78ZdtNc2fdZwkjUX0qOB8HqKZmEYixTGtsuqqxYU3MKnxtPfRC4ff"
    "eKDl59M/6tkJhTHB5xaxSXWCwIMgZsQrd252wVYUFgsZf57p7qjfd6LlTSuV1rMSUgiZccSm"
    "KERSFNtMl95def2ala5jSyk0LaKhdup456Ga5q9PdmmxiBYJi4BDBgGbutIFF+FoZGNDdQAB"
    "AkohpJR6KGH1D77/9CtvPfx83y+/x3INJBRczAdACtlmunjTrTeuW+N6NhIBgOBcYaquxbu/"
    "ON2+fW/ny8e4FNGELriYIfnTalUKqaps465qDhLHLQohIiGdPPi07Xjb9r0/fP6dnh1nKpuO"
    "MS2AFLJNa/WGshUbShzPIhrbKbgAhHjIuHi+92jj/nd2HzAHLylMmZIxk9tIkISY3LUVkGDC"
    "yxI456FQFDgMnO8lUuYcIgAgItu0blpfvOrOcttPT/A+JHQdy7h2UUPHs4lFWdwPpjTgWfwS"
    "ESQXyYZ7FTUkuRz/QARC06N17c3GklwnbSFNUy+zAIictL2spGjt5tvsIEWKAgCISIRIGLh+"
    "30+/KkyZQRCzOz4icjdI7qzWorrwORJxwR3XJlJQyA+eef37T77Scww+jelmACB0bbtg1fLS"
    "+5KOsAPfiy02CitKLM9kmsak+t6e17pPndGz4lMyMupZSOTZTrK+Wo2FVV27v7XpoSMtRbeX"
    "m86wFg5JJ3h390t/nOuJGrHJws4MgOg5Xl7+0jsat9W++uTy8tV+yq47+NTNVbeY1lAoEnWG"
    "Ukcfe3Hgtz41rE1QQ6Zdd8Q8quq3rFi/1ho2hZAg5Y6DTxRVrjOtIT2W+Ku398S+9svb5ZwB"
    "o+ewHN/xkAgJuR8g0I5De4oqyi6mLiy5ruCuxtrLehwTBMscMJKM8ffc91lIq21t6tyfXVF3"
    "T0FxYXrIRPqf3OYGmMwLXF/V1G0HHg8cLzX4z+RJhwEAISpEyvwmOwIpwUvZiKiqo7+LABKU"
    "EX9kCJBy7SHzkkpMZtKiMjkZouf7ulARgRFSaW5hTxBaaICXn30NUxhe7fH9X/4J7d/SMP8Y"
    "AAAAAElFTkSuQmCC")
geticon_seta_selecionar_32x32Data = icon_seta_selecionar_32x32.GetData
geticon_seta_selecionar_32x32Image = icon_seta_selecionar_32x32.GetImage
geticon_seta_selecionar_32x32Bitmap = icon_seta_selecionar_32x32.GetBitmap

