#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon_no_32x32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAIGNIUk0AAHolAACAgwAA+f8A"
    "AIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAGYktHRAD/AP8A/6C9p5MAAAAJcEhZcwAACxMA"
    "AAsTAQCanBgAAAWUSURBVFjDxZdriF1XFcd/a5997mvmzszN5N6ZmonTJtMkIzZNWlIoIlT8"
    "EGg/Kz6ooR/Uov0k1mdTQYMRpH6tkbaEGkFEqPFVLSKkdoiZRtJkSrSvMTSknRYzj3vvuY/z"
    "2MsP52YeyZ1Hk5buy4FzOees9V/r/19r7S2qqnyIywJMz7/FTGMWKwYUVD44h4IQuZhyfoAd"
    "m7ZinTom3/43M/XLeNbHeQavHaLGvM+uteM+BdCDz7b+YawCRgRrM2TDBL9apT46TKYaoJ73"
    "/kStDudbJFFENYURQ5g0MACqoCjOwN5Hn+Smv71IszyAxDF6gz+ShKiQw5+rQRThhKWnoikA"
    "BEziiHty/OvQlxl//Dgf/cMEzUoJEyfXHbmJE9qDfVQmprjzkSdQ7wqtS7pfJFqNYJshwZbN"
    "TDz+DXb+4veMPvM8zUoJSVxXSsW59OpSSJI4Wpv7qZx8mdt+9mvOffuLJLkM4lwa8dUAAJxn"
    "8OtN2oP9TBx5mB1Hn+WW3/ydqFjofLhkXD0h6skTFQskWT993gEiTokLWYZeOMeeQ08zefhr"
    "LGwfwTbacJW4V/wTVdQz2KBFe1ORU489RNSbR5IEFUkzp0o40IvXCim/+B+GT5yl5813iYoF"
    "XMZPwRlBnLL1jyc58/0HWNg5SqZaTym4Klu2G3fayUSrMkAwUsYGTZA0bUk+x61Hn2XHU3+i"
    "MPM/RB1RLs/MPXs4960v0BwexDZamCjmpYMHwAmZWg31u1dUVwCpJgwSxfhhvBhR1Jtjz6Gn"
    "GT/2DJEpkFg/FXCUcPNfTrBp6g2ef/J7NEbKeK0QE8bQyeqqQl1TxiKp88QR9vdwy29PsOvY"
    "72jlSiTWT2vaKRho5QcoXrrEvkeOgEtpSD2s3VbXb3cKznpk52rsfOI4MTlwLnW87B0TxYS5"
    "Piqnpxj56ymi3pXCXc34ugDEOZJCjvLkefouXCLJZFc6X2FPUYStfz6ZOu8avCy78zaQARTn"
    "GTadewNDsijG7mAVh0//KxfJzlZx1l6j+tSiIhh8KWwEgCCq5GdmUYTlXawbWDUe/kLQmSXr"
    "m9/4yHsP2wbRdXC+NwCKitAqDyCdkbpmtpwjKuav6Z43ACA1OnfbNhxmzdBUBENEdWwL7cE+"
    "TLS2ZjYEQI1gG23evetjBDcN4bWjtC2v8q4h4dL+u3DW2xBt62dABBPFtColXjtwLz4Bar1r"
    "InPWkmkFXB6/lTfv+wR+vbGhXdXab6im3dAz+NWA1+/fz/S9n6bQvIyoQz2TXiJkW1Xa/X2c"
    "/tFXSfKZzgjX1XtGZ606C8Q54nwW2wwX26qEMad/8iDBSIXtv3qObFBDREnweefO3bx08ADz"
    "u0bxaw3UCC7royadrquVZFcAJk5olgcYPf4C5VPnOfODB/DrTejM/KmHP89/P/spSlPTeM2Q"
    "4OYhZnePoSLLnGfoe/UiftDknbs/Tna2mlK3FgUqgiQJ7VKRyuR5dh05zutf2o+J4nSr3uE9"
    "M1+nWSlx8b67ufCZe7i8dwemHWKb7aVIVUnyGXYfPsbQxBTtzf3p9k7WACCJI+4tUJx+i72P"
    "PsXpH3+F6tgIXitcITr1DCaKySwEZObr2KC1ODmvCNdrh9S2bWHysYe4/fAvKf/zPK3NA0iS"
    "rAJAFbUemfk6+77zc17+5ueY3T1Gdq7Wnb+OONUzS46XZ9MY/IU61e0fYfKnX2fvD48y9I+z"
    "xIXcij2kudqoiWLOfvd+Zj55e2egXP/Z4EpA8+OjnDl4gOKFt9PSXFYYFtKDied5WFWSUpFq"
    "pUSu0UZ9e72+l1bGUKgGLNyxk/l942SDJrFvMVEauxWg3m4yV1vANzYdlU67pvVGltRr6Y1n"
    "CKOIHucjAtaI4Y7BMabj7CKAD3KJCGEUsrU0jPUs8mEfz/8PJGKj/+nhPokAAAAASUVORK5C"
    "YII=")
geticon_no_32x32Data = icon_no_32x32.GetData
geticon_no_32x32Image = icon_no_32x32.GetImage
geticon_no_32x32Bitmap = icon_no_32x32.GetBitmap

