#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon_normal = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAIGNIUk0AAHolAACAgwAA+f8A"
    "AIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAJcEhZcwAACxMAAAsTAQCanBgAAAPDSURBVEjH"
    "7VY9bx1VED0z9+77WtvrZ8cByzGJIr4CBIsUCFFFgISEFJBo6BE0SFBR0PADoKGnQEJCQgpK"
    "DQ2ioUBpQoPsKMGCBGInhNhO7Pd29747h2L3bZwERPMiGlZbzOzOPefOzLk7KyRxPy8PYH37"
    "yubghhedFJVAgo0WurOPzi17o53dWN3cmzxBitbRbNETUJFE/WQJAOgIJDwAAgSJSXajQdPJ"
    "Yf795ceMlCYBEiL/Yt/r3lGi22i+CqV3Za8DIwCI3K7WP9oVzn4XaEqswrzAnkHgxRi7rezc"
    "pcc//TZMtcUoIdK7as09tla7FiOMTBQEBDIyAPQKgk5bO8P115/devGERPMgLUnSK9eZ+vPv"
    "nepcv/nEJ2fW3nk1ZD2Qxz/+6sKbL+cLGZ0e/+j0+hsn9x5asHay+N2P2erltXdPtf+8WczP"
    "PPLZN8XczKXXnm/fuFXMTx858/3s+UvXX3kOpAcAIU13lw5urxzubGwN+/2dJ5fL2VSMw/7s"
    "9rHlfLFPlWG/v3Ps0O7RB2KnNX1xw2/nWytHOptb+WJ/cPDAYGlua+Vw59pOfjA7cPaCu3qj"
    "KpmvqxtNQnTDwg9yDVGL0g29RNMQXRncMKeIlsEVwQ8KkG5YyCi6Ye7y0g1yzUsNIz/I3bCo"
    "7qb/tUzFCBWq1qdEtYmgCiDV2aFTCKACgioQAQQiQtIpROqb4B0EAphRx91D/Vq4T4scPycA"
    "ETPIvjNEUrVRlIzR0ASJEVUEx0ptQKtQAgTqZRBjlVktsMptRGtsIhsCowgEQtbp30vGMYoA"
    "+yDuQgQAI1UrPq2zMlapSYwAhRQzjQYSoJipRamfRzHTGCmobIkmZqhcWv12zOfrqpGjXrvM"
    "0lHaZeLLrGftxHzBxIcsDdNdiUanZZaG6V7IerHlY7cVstQNypCllvjRVDfMpFrGkKWxnTTH"
    "2gNANGsnS6d/6P16LbmVT13ceOb9z6Eq0aYubqx88AW9A5n9dPnpD7+0lrfET61vuhDTX/5w"
    "eYhtP3P+yszqb4tfn9NyFDtJtvr72tsv6ChC4Kma7OZXTz41eOwQRgaV2PYuDxV/7LRcUVa7"
    "+fmtl1weqmZYK4FAi1B9oKzTkhglxEqjSNzOUj/ZK6jqq46F6e72QlZlJWSj4jvsWjm4u/9V"
    "2H4XsGGelIQ0PYjRD4pJjsxqB2zmgQhFJjfRbg+X+z7R/if47wk8ABVxqm6SP14gnKoC8ALs"
    "FsOtWzuJemIyFCJShpBaIgKvoifmH14ftSdNUC73H/TOy/3+ff8L2iMmjHWCGQEAAAAASUVO"
    "RK5CYII=")
geticon_normalData = icon_normal.GetData
geticon_normalImage = icon_normal.GetImage
geticon_normalBitmap = icon_normal.GetBitmap

