#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon_salvar = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAIGNIUk0AAHolAACAgwAA+f8A"
    "AIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAJcEhZcwAACxMAAAsTAQCanBgAAAThSURBVEjH"
    "tVZLa11VFP7WY59zX2lubtraQgt9W2oVrQgqHSo4KP6BTgR/h3Nn/gXBiYLgQDrQgVgQKw58"
    "YEtVVOI7adqkMcm995y991oOTpImaVKrtgvO5nAOe3/fWt+3197k7niYoQB+uv3H7HBBiR8U"
    "FIGipX3t/qnBYTW3z/+8Prv64AG6KI5NHlQHmCiwbgC4GxGD/tWKcHd3EFEDAIAT3KEAHHC4"
    "wx0gplCU1biCg51wHzgGM7cQQlCpx3WD0ay2pkETDhBRTvmjty7lpapst8Y+MjLcE8ThbXRK"
    "LW8t3jrzwtMnnzpTjyriOzM2AZgX3fLnL67PfTWTPFKlf7z28+8nZkJVOG1XZ2MBE3vx7Zf3"
    "3Tza7Rc/fnL12BOP0lY6um2mZTt0+FDRDl9+drXqVvVkjKPku8nvQMAYtQgfOXm8+tVijEoC"
    "+M4A7l4UYXZu9sbCjcnu4EZyJCABfC8NgmjK9stvv4nI3X+3ZwAHM6uEMY1fL944u/exajgW"
    "ZhCYQAARiIgIBDAI5G/inVUddcLEKMd/BnCAiENQA47Q0XN6eqimwrQOwI2zmkIz4OjQ+yOt"
    "RIQMm4uzSwZoMlADKsRVYOiVujR8CeD1FwLEGW4gUlERQaR/zgBwZlLVZE4gBhjM4B0BGLxG"
    "SFVEd3TzFoBmhxCzqHo23Ee4OxOJioqACL591+ygQcPIkd09G7JZo6oTEeDNC62vY0bMKiqq"
    "OzLY9pUAMLGKJvMySI8RuqVyU6IdwggEqKqIEJE7tiWxowbMIi2RSx98+P0PP8YYmRvKTSZY"
    "HyHMo/F4aWVlqt9nZiJiYRZ2d1jeBcDBTAIuJVy/+vW1b75q2ImqiGhT7OZpvoQw6PeFWVUt"
    "28ricmAhYe0Uu2pAzMqBmXvtXtDAIkFVQ9BtIaIhiIg7WFiD5pT/unlbSUJZTHYGu+8DYmKI"
    "iLlny6rq7rGuc84pJWFmZlYNRcHjcafT6bQ7xCSiayUCd/tdFkby3TUIknPeP7331YsXby8t"
    "ZbNCtY4xxVjH6GZzCws/zM+TyHA02jMxwSIqQoBnl1LKXtvMG1tsBaC1XiSqKedBv9/p9d67"
    "fLnbar303HPMXFVVjNHNMjCzuKghpJSIyMw0KIjcrdVri0qOa33pLu8R3H1q//6JqQEB46oa"
    "1fWoqmJKvinMrBmFeVjVt5aXmYUAYm7v6bjt0q7XWh1TYxJVLUJoHNNInFIyMzA3piSixj9q"
    "OaiaedlpaRlsUxfY2iqYYlWXRWu0vDxcXdWDB9x9eXUV7sTEwiKSzeBOzCkng5vlPb1uO7eK"
    "VinC7YnOtl5xB4CIcsyTjwy+nvv08amz3KF20do/mL7w/Hkh6rW7cECNzOEI4JZzQdrudnvt"
    "biiKpZuL8ws3n+hPWMqbT01Klt/97uP54W0lyZY7ve61K1/OXPl2eu803AeT/aBqZqOqauru"
    "bu6eUnJmZgbIzERkdvbP4+fPnjp3phpVzBwttZK88vSFzSVyZh6tDE8/8/ixJ0/nlB2ecnIH"
    "Acy8kej66GunC8HNHyufDSFU4y1XirUSMZEwS3PxYuSYlDgUAoCo5bj7mNqwxIa74W65jiqy"
    "7nZpOCkBK9VocXkpsPrGnP92iVynTkR1jF0LRFAmPjd94qdUbgH4f0FEdawPTx1QUXrY1/e/"
    "AamqUVWRrlgDAAAAAElFTkSuQmCC")
geticon_salvarData = icon_salvar.GetData
geticon_salvarImage = icon_salvar.GetImage
geticon_salvarBitmap = icon_salvar.GetBitmap

