#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon_momento = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAIGNIUk0AAHolAACAgwAA+f8A"
    "AIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAJcEhZcwAACxMAAAsTAQCanBgAAASCSURBVEjH"
    "1ZZNbFRVFIDPufe+eW/edNqhAwPFEJBfpQiBQQYoCoiUCMQVCa4MG92pJBI0RogRQ8SF0YUL"
    "F8QYDNGAGhNrQFOwigIiIYbEMrS0FmkpaJmZ9+bN9P3ce1y8dmgLhS6GhWd18u6557vn776L"
    "RAQPUgQAdOX7+ku3BLJqoRDQV8GUaGJ+/QyhSP12vb3fqT4gBpHZdQ2CABiixkR1AQDAAiAC"
    "AQAEQEAE1axGxRurns+7y/8fICoaKoVVqgLx226HNSI3HpdCAyIAAsCK8Tj6WJ+VJVTKcJxR"
    "ACSSmrb0i68nd3RJPUKIoR0AKM6ZkkAAAIozVBRGSYxVbAiRGDKpCJH7fjE1+cJz2wBxuAYE"
    "hMiknHXy9/7GRy9veDKSL3HH61y35uqK9NQLHTfnzu3JLL+ydnV99pozKdndlLmytgnLUh9w"
    "Otc1dTdlyvFEoqOvc13TtWVLelYuf+jMRd0uEmdhowpAAAJgqEz+1+rH+xYvTF3q8KNGtnm9"
    "btnzWtu612TshpRnmnPafv17xZKrmXQQicRv3NQtO9v8FHc93zAMx8puXG/m8oGuN355HIlo"
    "yC8MRerGYn2LG9OHjrAg0O2iNugaBcuwbOG6hl00CrZRsITr6o5jFOxowdJKZa08aBSsqGVF"
    "HEe4rnkrr7jY8O4HTkO9MyXJgyDMEgsTqtvFP7Y/OyXbmcpe8c0oIRJjxBggEhvWAQlZ5TtU"
    "bBhjUtrTUplPPqvtv/H9nl3M90fPAQILAjceb9+6MX3oiB81Jt6vBIhSOsn6Rd98N/vUmZZ3"
    "3oyUSkwpGgUAIM7NW7n2Z5428tbDp866NbGwQ+4rTEkvFpt59nz68NFv9+8FRBbIsMdGAcJR"
    "UJxd3LZlZuv5wXgtAuC9w0BAImIs0CKJrt4Tu192kvXa4CBxDiM23gZITYs45d4li07v2tHY"
    "cowA1VCrjTNcRIpzlGrVwU9b9+wcmD1LLxYV5ygljCDcBiARcRYtWKdfeN6aNrV533ulSQkE"
    "gLDl7gxAUbmudtPbB/oXPvLnlmZzIKeEAIDKiN2RovBYjJkDuRO7XxGev/79j0qJOkBAqcKc"
    "VM7OgsCZnFz74cfE2M8vvWgO5JTgQ4uII4O+222KaFjWsbdeS1zrnd/yk+RaOVGHRKgUKgUI"
    "fjRamN6w9POvUpcuH9+zO5ovEBvvjrobgBCRSHjeD2+8enH75k37DqQPH/VipmeabrwGCGae"
    "Pbfg2EmUqvX1nUxKVDQmLaNOGyh5NPvjP6X8mH8yEhFiua422d2z8uAh7nnm9YIf15WhSSH6"
    "Fy5o37zRrakRrjuyKSv95avACPiO9FYxHjm8U2MDOXtqqmX/3jltv8w6fa536WM3Fsyzpjco"
    "wXW7KDzvTu9jRNx7WQnOPS/272BPZnnXE6tYIIXr6raNRIoxGj8zEwWENVecR5wSFhXh8HV0"
    "/20TB4QZY0jAJ+x2NIAhcsZ4NR9eQMAZYwAgEKDolnN2QWOCoDoIRPR8P6Y0RBAM2bLk3K5A"
    "rzbAmzFpmuACH/Tz/T8wyyuaruenlgAAAABJRU5ErkJggg==")
geticon_momentoData = icon_momento.GetData
geticon_momentoImage = icon_momento.GetImage
geticon_momentoBitmap = icon_momento.GetBitmap

