#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon_iniercia = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAIGNIUk0AAHolAACAgwAA+f8A"
    "AIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAJcEhZcwAACxMAAAsTAQCanBgAAAJVSURBVEjH"
    "7Za/a1NRFMe/59yb1iQkTZtWK1jEInZRCgq6KCiIi4I6OYmTg5uOFWfxByhOgvUfqO4ubqII"
    "iqvdKsWiQcRa+n4k7917jkOKxSQvbWy75az38v3c9z3wvl9SVezkWAALv7/Vol+WeLtQBErF"
    "jeUrh0YmrKh8+D5fC7cfUMTA5NBeqwAT5dhmAbz3XbSYmYjaAQDYQRUWgAIKVXTYBhGVqxUQ"
    "VLT9iJji1ShNknbGXzWb+TZVNiYOorn7z9JGOljY1aLukjQOorNXLx6YnkqiBjF1lMkEKACC"
    "iHz9vFBbXApXgpYL+VKxUMifunSOmRXatKUHABGJl0KpeHvuMTF9fPXm6a27bA0zuyQ9f/3K"
    "5ZvXiOCcq4cxM2cuCV1HVeMwSurJ4ZPHhkaHxXlxHsD0mRMmZ6Mgcs61L6AHAABmVhERyQ0O"
    "rFkHQNQ7x0xZzvQAaEq2PJM2Vt48YGvTB/QBfUAfsImxG94QEQJ86iRdD2dREe/FCxNt6XdN"
    "RPlSsbJ7VETC1QBAMxrjMKqMVQtDJZOz6NqsbHd1l7r5t++Xf/z89PpdI64TkXoBMHdvtvZl"
    "qbKnOnlkqjw24rNjJzuTVY019eVoduZhHETExMasgYHa4tKLB89F5MajmeMXTocrKZneM9k7"
    "XygX77x8AoWqisj6KRMTi0h5pFKPYjaZVlsATGSYTcfiZXh8/75sE+FTpyL4t7MQoDDNJmAJ"
    "CBrx8upKjq2iA6K9crV8aHt2ElGSpkXJEcEy8dHqwQU3mAX4jyGiJE0mhsetsbTT9f0PIzsO"
    "onAZsb0AAAAASUVORK5CYII=")
geticon_inierciaData = icon_iniercia.GetData
geticon_inierciaImage = icon_iniercia.GetImage
geticon_inierciaBitmap = icon_iniercia.GetBitmap

