#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon_mod_elasticidade = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAIGNIUk0AAHolAACAgwAA+f8A"
    "AIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAJcEhZcwAACxMAAAsTAQCanBgAAAKrSURBVEjH"
    "tZa/a1RBEMe/M7vvYkw0lwsXkkACRomoiBqLFNr4N4ggWImFioUgiGCw0jaNIIK12Fha2Qo2"
    "prSwi4U/LhKJRu/eu719u2Pxcoa7vD3vzstUj32785lfO7MkIthL0QDWfn5djzc18aBQBLI+"
    "LQ8XF0qz2ot/V/mwXhs8YASF+bFpLQATRazbAN677jUyqzYAAE4hAg1AAIEIWrIxPDpKTN1o"
    "F5F6LW5fbGrToWPPHz75/uVbVIg6VAERpTYtlscv3b2mtM7dqXOPOefev1nd+FQhJvGdACJS"
    "mipfvHNVRYAXULvTHMqSUgyAFbNidAwVEYiCO4Ih8t4D8M6Ll/LsdGGosDsCRGQbdmJmEkQQ"
    "IA8TBOw4A7m+cu/QyaMmTojzPRaRUKr+CcjON1X0fu27ArjUeue8c5QHYGb0kYOdAAH790UH"
    "SmO6EHFeiOq1xDsfKoSuPFh9/fbzx4o1jZxqETlx/uxI8aBP036SLBAAr5697ODg/RcrY5Ml"
    "Yy31VUUAwFqFKt07R1mNBqQrgE87NT7JXOkXQIBcWb4xMz/XMIaI0WotgSbnpq2xoSvSlQcL"
    "S6cOnz5magkxtVorAExixPv/ClG9lsS/qqGbzAHbewBk7SyT3X9FpJ9m12qjymSvepFJ6kkt"
    "7tDsoqEC95tkAfD09qPQwCImE9dvPX5w/NxiUq3txgQB2RxnpYSkulUN9VFiFu9Ta6nHXiTO"
    "OQDeuQ4jsxvJAYgIMZ+5sLRZ2YgKUTbaRLanFiSrKBHZnpRpwxbLJZc6Qi+96PLyTWYCctoM"
    "NRezDyIycdKom9xnjgbARIpZtT68TDX+q6XdxeaiNBnMpJVqtUBlCdcEVE3y4/dWxFowmMcj"
    "ETWsHfERETQTL04cWUuHBg1ozI5PaaVpr5/vfwAm6T0J+3yI8wAAAABJRU5ErkJggg==")
geticon_mod_elasticidadeData = icon_mod_elasticidade.GetData
geticon_mod_elasticidadeImage = icon_mod_elasticidade.GetImage
geticon_mod_elasticidadeBitmap = icon_mod_elasticidade.GetBitmap

