#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icone_seta_calcular_32x32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAIGNIUk0AAHolAACAgwAA+f8A"
    "AIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAJcEhZcwAACxMAAAsTAQCanBgAAARaSURBVEjH"
    "tVZNbFRlFD3nvm+mQ2unf1CqiFqhlVCkKISIIKjEHwwxUcPCsCAYYiLGBS7YSYwL3bjVtRvj"
    "wrUrTYgLIREiySSImhQwLZSZttPODMO8v++7Lt50KNJX2ibcTCYvmXnfueece+93qap4mGEA"
    "XJ27eetOOUNz708KcHWHEghctG5N93DvRuPU/T555Va9bNW6e9moKrkaDCEF0oHs012PGgWE"
    "zIp5tv+ZnMkmGAolYJiJXQgQK4ER0o/DQmmMEVRhCKgqiB39mzuz7QolCODP6vn1uSf6skMr"
    "0ip5vRbeKZTGFApCEtFUYVUBOFWrDsCt+o2fbnxfqJwLXQjAqnPqnOoDP8khgLJlcota6xuA"
    "ERMiKMydK/rjo117+3OPA6oAl2STeLjQObPEn5WxY3zTvzoXloY6Rrd27c56OYUDyGWLlgrg"
    "YKMooBES1Xi2UP1t0r+2vXvfhvZNgCrcvLyrBQDj0IbqBKCQEcLxeGwmmhx6ZHS0e3/O61gm"
    "lXQGGltESZpUAoRlYMNL0a8TjX929b72ZPvW5VBJBbCIY0QKsmksk3awluP1f6eC77bkd+7u"
    "PdTu5VUdmEolHUCjCIFrtkDzfQKAKDSMgwvls9fql/f1vT3UuQtQp04oKwCIEIXWN16S3N0E"
    "qSSpUFVMBBM/Tn4zUnvh1f4jnabXqcO9NbqkB4hiG7lY6CWzQklpSjUf6jRWPT/189+1P15f"
    "f3RH937F/2fzEh44pxaI1SajRAALLJgazaZSgZlpTP9w/euL+V/eGjj+WPvgQpjUAqi6UjWe"
    "sdoAI5FYJKKElJCIiIgIwQAMgJASZQyrtnZ5plDxy0DS8ksxUIC1uFKsT1RQM8Zr89qMlxEa"
    "TzxDA8DBoTlXZM6fvd1ovJI/cnT4487OPAAucDu90WKqg1KDKAhCXwmCpIIkhLBCL7JaqpcG"
    "sOnk4JcHNr+pmUVqKd1khzjUUCylKbyQCipU6Kicrs/6dXt44NjxbafX9vU5OIK8r1LTyzRy"
    "se8MnZN5b0kSHr1GEE9VpgfbRk5uO/PS0EFk7yau910e6QysQwR6oE1aDUKqk2Jl1gU48tRH"
    "x5//tHdtj8JBuWiLpQMoQMShixuqGaqCHoRerR4UyzMjPTs/2fvZnuH9mlFV12yO9EhlEAcu"
    "9DWwSiECKU5Pe1Hbie2nj+05me/JN0cpHzyxFwFIVIx9aAOGmWrt9lSpvHPDi6cOf75jeJdy"
    "PvHlRboHARiayWLRRGtOvfzF0QMncu05p466rMQXAWjd16oqxO25O9evjL+x9b1T75zZMjji"
    "1FlnSWqyhaSEQj1S7+tkJeHdvfQJIB/0fvXut+8f+rA5ox9kZkve1iHJs1FARIQsTI21Fi+n"
    "7uCBD9Z1DVwo/aVuBYpjfvESoUdBsnjVg0a5VjlbvdhaHQmKSHT9kqzk6AUYQkWHy5AwQnmu"
    "b3NX3NbmZRZK21rxVhEk/dDf2DNgPMOHvb7/B908YPYWeVZsAAAAAElFTkSuQmCC")
geticone_seta_calcular_32x32Data = icone_seta_calcular_32x32.GetData
geticone_seta_calcular_32x32Image = icone_seta_calcular_32x32.GetImage
geticone_seta_calcular_32x32Bitmap = icone_seta_calcular_32x32.GetBitmap

