#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

Crosshair_Cursor_Link = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAMZJ"
    "REFUWIXtlUsOwyAMRHHSS4Ahvf+xGj49ReuuQEQlWRCEhcRsEAvg4TEDwLIKTi2spw8NgEoS"
    "GwAqSdZRE4hxLZgArAAAcBi7A7QUOwDU/gUaFTkfbntQDdBKj3xylmyx2fIbG41knU9zjSqt"
    "Jfrfxod3sVqpAjFer7SZRTgfwGik1/4Rz20V1nnQqGi338u1RkMR4mABawW4VP0M8xt3B4ie"
    "t4BgD6IxAWKXl7q9C0BLTQB2gOokRCXpLF67ALQSuwUT4AdpoU7LMxHIuAAAAABJRU5ErkJg"
    "gg==")
getCrosshair_Cursor_LinkData = Crosshair_Cursor_Link.GetData
getCrosshair_Cursor_LinkImage = Crosshair_Cursor_Link.GetImage
getCrosshair_Cursor_LinkBitmap = Crosshair_Cursor_Link.GetBitmap

